#!/bin/bash

set -e

echo "=============================="
echo "Updating system..."
echo "=============================="
sudo yum update -y

echo "=============================="
echo "Installing Java 21..."
echo "=============================="
sudo yum install -y java-21-amazon-corretto-devel wget tar

java -version

echo "=============================="
echo "Creating Nexus user..."
echo "=============================="
sudo useradd --system --create-home --shell /bin/bash nexus || true

echo "=============================="
echo "Creating application directory..."
echo "=============================="
sudo mkdir -p /app
cd /app

echo "=============================="
echo "Downloading Nexus..."
echo "=============================="
wget https://download.sonatype.com/nexus/3/nexus-3.79.1-04-linux-x86_64.tar.gz

echo "=============================="
echo "Extracting Nexus..."
echo "=============================="
tar -xzf nexus-3.79.1-04-linux-x86_64.tar.gz

mv nexus-3.79.1-04 nexus

mkdir -p /app/sonatype-work/nexus3

echo "=============================="
echo "Setting permissions..."
echo "=============================="
sudo chown -R nexus:nexus /app

echo "=============================="
echo "Configuring Nexus..."
echo "=============================="

sudo sed -i 's/^#run_as_user=""/run_as_user="nexus"/' /app/nexus/bin/nexus

cat <<EOF | sudo tee /app/nexus/bin/nexus.rc
nexus-data=/app/sonatype-work/nexus3
EOF

echo "=============================="
echo "Creating systemd service..."
echo "=============================="

sudo tee /etc/systemd/system/nexus.service > /dev/null <<EOF
[Unit]
Description=Nexus Repository Manager
After=network.target

[Service]
Type=forking
User=nexus
Group=nexus
LimitNOFILE=65536
ExecStart=/app/nexus/bin/nexus start
ExecStop=/app/nexus/bin/nexus stop
Restart=on-failure
TimeoutStartSec=600
TimeoutStopSec=600

[Install]
WantedBy=multi-user.target
EOF

echo "=============================="
echo "Reloading systemd..."
echo "=============================="

sudo systemctl daemon-reload
sudo systemctl enable nexus
sudo systemctl start nexus

sleep 20

echo "=============================="
echo "Service Status"
echo "=============================="

sudo systemctl status nexus --no-pager

echo
echo "=============================="
echo "Java Version"
echo "=============================="
java -version

echo
echo "=============================="
echo "Nexus Port Check"
echo "=============================="
sudo ss -tulpn | grep 8081 || true

echo
echo "If Nexus is running, open:"
echo "http://<EC2-PUBLIC-IP>:8081"
